name: Compilação Orbital G18
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fabricando APK e RPA
        uses: Ayowel/renpy-build-action@v1.4.0
        with:
          platform: android
          project-dir: .
          output-dir: build_output
      - uses: actions/upload-artifact@v4
        with:
          name: Mod-Pronto-G18
          path: build_output/*.apk
