name: Forca_Bruta_G18_Definitivo_V4
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 1. Pegando arquivos
        uses: actions/checkout@v4

      - name: 2. Criando Memória Virtual (O Tanque de Oxigênio)
        run: |
          sudo fallocate -l 8G /swapfile_extra
          sudo chmod 600 /swapfile_extra
          sudo mkswap /swapfile_extra
          sudo swapon /swapfile_extra
          echo "Tanque de memória extra ativado:"
          free -h

      - name: 3. Instalando Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 4. Baixando Motor e Preparando Hangar
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libglu1 libpulse0 libasound2
          
          wget -q https://www.renpy.org/dl/8.2.1/renpy-8.2.1-sdk.tar.bz2
          tar xf renpy-8.2.1-sdk.tar.bz2
          mv renpy-8.2.1-sdk renpy_sdk
          
          wget -q https://www.renpy.org/dl/8.2.1/renpy-8.2.1-rapt.zip
          unzip -q renpy-8.2.1-rapt.zip
          mv renpy-8.2.1-rapt renpy_sdk/rapt || mv rapt renpy_sdk/rapt

      - name: 5. Criando a Identidade do APK
        run: |
          cat <<EOF > android.json
          {
              "name": "Grandmas House",
              "icon_name": "Grandmas House",
              "package": "gm18.grandmashouse",
              "version": "0.102",
              "numeric_version": 1,
              "orientation": "sensorLandscape",
              "update_keystore": false,
              "google_play_key": "",
              "google_play_salt": ""
          }
          EOF

      - name: 6. Compilando o APK (Fila Indiana Segura)
        env:
          # A FÓRMULA MÁGICA PARA JOGOS PESADOS:
          # -Dorg.gradle.parallel=false (Desliga o modo apressado)
          # -Dorg.gradle.workers.max=1 (Usa apenas 1 trabalhador para não estourar a RAM)
          # -Xmx4g (Libera 4GB limpos de RAM + o Swap)
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.workers.max=1 -Xmx4g"
        run: |
          mkdir -p build_output
          chmod +x renpy_sdk/renpy.sh
          yes | xvfb-run ./renpy_sdk/renpy.sh renpy_sdk/launcher android_build . --destination $GITHUB_WORKSPACE/build_output

      - name: 7. Entrega da Carga
        uses: actions/upload-artifact@v4
        with:
          name: APK_Final_G18
          path: build_output/*.apk
