name: Forca_Bruta_G18
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 1. Pegando arquivos
        uses: actions/checkout@v4

      - name: 2. Preparando Hangar e Python
        run: |
          sudo apt-get update && sudo apt-get install -y unzip python3-pip
          # Instalando a peça que faltava para o Ren'Py abrir
          python3 -m pip install future
          echo "Hangar e bibliotecas prontos."

      - name: 3. Instalando Motor e RAPT
        run: |
          wget -q https://www.renpy.org/dl/8.2.1/renpy-8.2.1-sdk.tar.bz2
          tar xf renpy-8.2.1-sdk.tar.bz2
          mv renpy-8.2.1-sdk renpy_sdk
          wget -q https://www.renpy.org/dl/8.2.1/renpy-8.2.1-rapt.zip
          unzip -q renpy-8.2.1-rapt.zip
          mv rapt* renpy_sdk/rapt

      - name: 4. Cuspindo Código (O SHOW COMEÇA AQUI)
        run: |
          # Agora com a biblioteca 'future', o comando vai voar
          python3 renpy_sdk/renpy.py renpy_sdk/launcher distribute . --destination build_output --platforms android

      - name: 5. Entrega da Carga
        uses: actions/upload-artifact@v4
        with:
          name: APK_Final_GamesMais18
          path: build_output/*.apk
