name: Gerador_APK_GamesMais18
on: [push]

env:
  # Isso é crucial: desliga o Android padrão do GitHub para não dar conflito com o do Ren'Py
  ANDROID_NDK_HOME: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Pegando os arquivos do Mod
        uses: actions/checkout@v4
        with:
          path: projeto_g18 # Isola o seu jogo numa pasta limpa

      - name: 2. Instalando o Java (Coração do Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3. Construindo o APK (O Plugin Oficial)
        uses: Ayowel/renpy-setup-action@v2.0.1
        with:
          action: android_build
          install_dir: motor_renpy
          game: projeto_g18
          out_dir: build_output
          android_sdk: true
          android_sdk_owner: "GamesMais18"

      - name: 4. Entrega da Carga
        uses: actions/upload-artifact@v4
        with:
          name: APK_GamesMais18_Final
          path: build_output
