name: Missao Final G18
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizando Projeto
        uses: actions/checkout@v4

      - name: Terminal em Tempo Real
        uses: Ayowel/renpy-build-action@v1.4.0
        with:
          platform: android
          project-dir: .
          output-dir: build_output

      - name: Gerando APK
        uses: actions/upload-artifact@v4
        with:
          name: Mod-GamesMais18
          path: build_output/*.apk
