name: Vitoria_G18_V3
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: TERMINAL_VIVO
        uses: "Ayowel/renpy-build-action@v1.5.1"
        with:
          platform: android
          project-dir: .
          output-dir: build_output
