name: Compilacao_Final_G18
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Pegando arquivos
        uses: actions/checkout@v4

      - name: 2. Instalando Java e Unzip
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          echo "Java está pronto."

      - name: 3. Baixando Motor e Ferramenta Android (RAPT)
        run: |
          # Baixando o SDK
          wget -q https://www.renpy.org/dl/8.2.1/renpy-8.2.1-sdk.tar.bz2
          tar xf renpy-8.2.1-sdk.tar.bz2
          mv renpy-8.2.1-sdk renpy_sdk
          # Baixando o RAPT (Essencial para o APK)
          wget -q https://www.renpy.org/dl/8.2.1/renpy-8.2.1-rapt.zip
          unzip -q renpy-8.2.1-rapt.zip
          mv renpy-8.2.1-rapt renpy_sdk/rapt

      - name: 4. Cuspindo Código (O SHOW COMEÇA AQUI)
        run: |
          # O comando "mágico" para o Ren'Py 8 compilar via terminal
          python3 renpy_sdk/renpy.py renpy_sdk/launcher distribute . --destination build_output --platforms android

      - name: 5. Entrega do APK
        uses: actions/upload-artifact@v4
        with:
          name: APK_GamesMais18_Pronto
          path: build_output/*.apk
